### ISSUE TITLE
Can't extract selector with double underscore, when there is same selector except that the double underscore part is double dash instead

### ISSUE THREAD

**Issue by chbybnwr** [qodesmith/purgecss-whitelister#4]
I used this to firebaseui css file. Everything extracted except mdl-progress__indeterminate selector, then I noticed that it also has mdl-progress--indeterminate that probably causing some kind of conflict.

**Comment by qodesmith** [comment]
@chabib  I just downloaded the `firebase-ui.css` from [here](https://github.com/firebase/firebaseui-web/blob/master/stylesheet/firebase-ui.css). It doesn't contain either `mdl-progress__indeterminate` or `mdl-progress--indeterminate` classes. Is this the same file you're using?

**Comment by chbybnwr** [comment]
I use the dist version in firebaseui npm package. I think you have to install it to see it. Or you can see directly in this [material design lite repo](https://github.com/google/material-design-lite/blob/60f441a22ed98ed2c03f6179adf460d888bf459f/src/progress/_progress.scss#L54-L86), which contains these lines:

```css
@supports (-webkit-appearance:none) {
  .mdl-progress:not(.mdl-progress--indeterminate):not(.mdl-progress--indeterminate) > .auxbar,
  .mdl-progress:not(.mdl-progress__indeterminate):not(.mdl-progress__indeterminate) > .auxbar {
    background-image: linear-gradient(to right, $progress-secondary-color, $progress-secondary-color),
      linear-gradient(to right, $progress-main-color, $progress-main-color);
    mask: url('#{$progress-image-path}/buffer.svg?embed');
  }
}

.mdl-progress:not(.mdl-progress--indeterminate) > .auxbar,
.mdl-progress:not(.mdl-progress__indeterminate) > .auxbar {
  background-image: linear-gradient(to right, $progress-fallback-buffer-color, $progress-fallback-buffer-color),
    linear-gradient(to right, $progress-main-color, $progress-main-color);
}

.mdl-progress.mdl-progress--indeterminate > .bar1,
.mdl-progress.mdl-progress__indeterminate > .bar1 {
  background-color: $progress-main-color;
  animation-name: indeterminate1;
  animation-duration: 2s;
  animation-iteration-count: infinite;
  animation-timing-function: linear;
}

.mdl-progress.mdl-progress--indeterminate > .bar3,
.mdl-progress.mdl-progress__indeterminate > .bar3 {
  background-image: none;
  background-color: $progress-main-color;
  animation-name: indeterminate2;
  animation-duration: 2s;
  animation-iteration-count: infinite;
  animation-timing-function: linear;
}
```
